export 'package:flutter/material.dart';
export 'package:flutter_application_1/screens/register_screen.dart';
export 'package:flutter_application_1/widgets/body_login.dart';
export 'package:flutter_application_1/widgets/custom_clipper.dart';
export 'package:flutter_application_1/widgets/register_body.dart';
export 'package:flutter_application_1/screens/home_screen.dart';
export 'package:flutter_application_1/screens/login_screen.dart';
export 'package:flutter_application_1/widgets/custom_button.dart';
export 'package:flutter_application_1/widgets/custom_text_form.dart';
